server:
  servlet:
    context-path: /bff--site-shoes
  port: 5000
spring:
  devtools:
    restart:
      enabled: false
  application:
    name: bff--site-shoes
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    banner-mode: 'OFF'
  config:
    import: "configserver:${CONFIG_SERVER:http://localhost:8888/config/}"
  cloud:
    allow-override: true
    config:
      username: develop
      password: develop
      name: "bff--site-shoes"
      label: master
    retry:
      max-attempts: 5000
      initial-interval: 1500
      multiplier: 1.5
      compatibility-verifier:
        enabled=false:
info:
  app:
    name: "@project.name@"
    version: "@project.version@"
    description: "@project.description@ "
    base-package: "com.shoesclick.bff.site.shoes"

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    prefer-ip-address: 'true'

logging:
  level:
    org.springframework.web: DEBUG

management:
  server:
    port: 9090
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, shutdown, prometheus
  endpoint:
    shutdown:
      enabled: true
      health:
        show-details: always
        probes:
          enabled: true
        group:
          readiness:
            include: diskSpace

opentracing:
  service-name: bff-site-shoes-app
  jaeger:
    http-sender:
      url: ${JAEGER_HOST:http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces