apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff--site-shoes-deployment
  namespace: shoes-eks
spec:
  selector:
    matchLabels:
      app: bff--site-shoes
  template: 
    metadata:
        name: bff--site-shoes
        labels:
          app: bff--site-shoes
    spec:
        containers:
          - name: bff--site-shoes-container
            image: $dck-accountid/$dck-repository:bff--site-shoes-$githash
            env:
              - name: SPRING_PROFILES_ACTIVE
                value: "dev"
              - name: CONFIG_SERVER
                value: "http://svc-swapiconfigserver.shoes-eks.svc.cluster.local/config/"
            ports:
              - containerPort: 5000
              - containerPort: 9090
            livenessProbe:
              httpGet:
                path: /actuator/health
                port: 9090
              initialDelaySeconds: 120
              periodSeconds: 60
              timeoutSeconds: 10
              successThreshold: 1
              failureThreshold: 2
            readinessProbe:
              httpGet:
                path: /actuator/health
                port: 9090
              initialDelaySeconds: 120
              periodSeconds: 10
              timeoutSeconds: 10
